import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { sassPlugin } from "esbuild-sass-plugin";
import copyStaticFiles from "esbuild-copy-static-files";
import path from "path";
import packageJson from "./package.json" with { type: "json" };
import { writeFileSync } from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const outdir = prod
	? "./dist/"
	: // Assumed local path. Update this to the path of your local development vault
	  "E:/Documents/PersonalObsidianVault/.obsidian/plugins/obsidian-canvas-dailynote/";

export const preactResolvePlugin = (
	options = {
		replaceReact: true,
		keepDevtools: process.env.NODE_ENV === "development",
	}
) => ({
	name: "preact-compat resolver",
	setup(build) {
		if (!options.replaceReact || !options.keepDevtools) {
			build.onLoad({ filter: /^preact\/debug$/ }, () => {
				return { contents: "" };
			});
		}
		if (options.replaceReact) {
			build.onResolve(
				{ filter: /^(react|react-dom|preact\/compat)$/ },
				(_args) => {
					let dest = path.join(
						process.cwd(),
						"node_modules/preact/compat/dist/compat.module.js"
					);
					return { path: dest };
				}
			);
			build.onResolve({ filter: /^(react\/jsx-runtime)$/ }, (_args) => {
				let dest = path.join(
					process.cwd(),
					"node_modules/preact/compat/jsx-runtime.mjs"
				);
				return { path: dest };
			});
			build.onResolve({ filter: /^(react-dom\/client)$/ }, (_args) => {
				let dest = path.join(
					process.cwd(),
					"node_modules/preact/compat/client.mjs"
				);
				return { path: dest };
			});
		}
	},
});


const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts", "styles.scss"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	minify: prod,
	metafile: prod,
	plugins: [
		sassPlugin(),
		prod && preactResolvePlugin(),
		copyStaticFiles({
			src: "./manifest.json",
			dest: path.join(outdir, "manifest.json"),
		}),
	],
	outdir: outdir,
	define: {
		"process.env.NODE_ENV": prod ? '"production"' : '"development"',
		"process.env.PLUGIN_VERSION": `"${packageJson.version}"`,
		"process.env.EMULATE_MOBILE": prod
			? "false"
			: process.argv.includes("--mobile").toString(),
	},
});

if (prod) {
	const result = await context.rebuild();
	writeFileSync(
		"./dist/meta.json",
		JSON.stringify({ ...result.metafile }),
	);
	process.exit(0);
} else {
	await context.watch();
	await context.serve(); // This enables the "live reload"
}
